name: Resyntax Review Submission

# The Resyntax integration is split into two workflows. See ./resyntax-analyze.yml for details about
# why it works this way.

on:
  workflow_run:
    workflows: ["Resyntax Analysis"]
    types:
      - completed

jobs:
  review:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Download Resyntax analysis
        uses: actions/download-artifact@v3.0.0
        with:
          name: resyntax-review
      - name: Create pull request review
        uses: actions/github-script@v6.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var create_review_request = require('./resyntax-review.json');
            await github.rest.pulls.createReview(create_review_request);
